# Generated by Django 3.2.3 on 2021-07-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbvviews',
            name='type',
            field=models.CharField(choices=[('base_view', 'Base View'), ('generic_display_views', 'Generic Display Views'), ('parrot', 'Generic Editing Views'), ('unknown', 'Unknown')], default='unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='cbvviews',
            name='name',
            field=models.CharField(choices=[('view', 'View'), ('template_view', 'Template View'), ('redirect_view', 'Redirect View'), ('detail_view', 'Detail View'), ('form_view', 'Form View'), ('create_view', 'Create View'), ('update_view', 'Update View'), ('delete_view', 'Delete View'), ('unknown', 'Unknown')], default='unknown', max_length=25),
        ),
    ]
