# Generated by Django 3.2.3 on 2021-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0002_auto_20210711_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbvviews',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
