# Generated by Django 3.2.3 on 2021-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0003_alter_cbvviews_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbvviews',
            name='name',
            field=models.CharField(choices=[('view', 'View'), ('template view', 'Template View'), ('redirect view', 'Redirect View'), ('detail view', 'Detail View'), ('form view', 'Form View'), ('create view', 'Create View'), ('update view', 'Update View'), ('delete view', 'Delete View'), ('unknown', 'Unknown')], default='unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='cbvviews',
            name='type',
            field=models.CharField(choices=[('base_view', 'Base View'), ('generic display views', 'Generic Display Views'), ('parrot', 'Generic Editing Views'), ('unknown', 'Unknown')], default='unknown', max_length=25),
        ),
    ]
