# Generated by Django 3.2.3 on 2021-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0004_auto_20210711_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbvviews',
            name='name',
            field=models.CharField(choices=[('View', 'View'), ('Template view', 'Template View'), ('Redirect view', 'Redirect View'), ('Detail view', 'Detail View'), ('Form view', 'Form View'), ('Create view', 'Create View'), ('Update view', 'Update View'), ('Delete view', 'Delete View'), ('Unknown', 'Unknown')], default='Unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='cbvviews',
            name='type',
            field=models.CharField(choices=[('Base view', 'Base View'), ('Generic display views', 'Generic Display Views'), ('Generic editing views', 'Generic Editing Views'), ('Unknown', 'Unknown')], default='Unknown', max_length=25),
        ),
    ]
