# Generated by Django 3.2.3 on 2021-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0005_auto_20210711_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbvviews',
            name='example',
            field=models.ImageField(upload_to='views'),
        ),
    ]
